import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'
import { useAuth } from '../../context/AuthContext'
import { getActiveShips } from '../../services/shipService'
import { getActiveBLsByShip } from '../../services/blService'
import { createBL, createProduct, createShip, createUser, getProducts, getUsers, resetUserPassword, updateUserRole, updateUserStatus } from '../../services/adminService'
import type { Ship } from '../../types/ships'
import type { BL } from '../../types/bls'
import type { Product, UserSummary } from '../../types/admin'
import './AdminPage.css'

function errorMessage(error: unknown) { if (axios.isAxiosError(error)) return String(error.response?.data?.error ?? error.response?.data?.message ?? error.message); return 'Ocurrió un error inesperado.' }
function roleName(role: string | number) { if (role === 1 || role === 'Administrator') return 'Administrator'; if (role === 2 || role === 'Yard') return 'Yard'; return 'User' }
function roleValue(role: string | number) { if (role === 1 || role === 'Administrator') return 1; if (role === 2 || role === 'Yard') return 2; return 3 }

export function AdminPage() {
  const navigate = useNavigate(); const { user } = useAuth()
  const [ships,setShips]=useState<Ship[]>([]); const [products,setProducts]=useState<Product[]>([]); const [users,setUsers]=useState<UserSummary[]>([]); const [bls,setBLs]=useState<BL[]>([])
  const [shipName,setShipName]=useState(''); const [productName,setProductName]=useState(''); const [bl,setBL]=useState({code:'',totalQuantity:'',shipId:'',productId:''}); const [newUser,setNewUser]=useState({uid:'',firstName:'',lastName:'',password:'',role:3}); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  const [resetUserId,setResetUserId]=useState(''); const [resetPassword,setResetPassword]=useState('')
  async function loadBLs(shipId:string){if(!shipId){setBLs([]);return} try{setBLs(await getActiveBLsByShip(shipId))}catch(e){setError(errorMessage(e));setBLs([])}}
  async function load(){try{const [shipData,productData,userData]=await Promise.all([getActiveShips(),getProducts(),getUsers()]);setShips(shipData);setProducts(productData);setUsers(userData);const selectedShipId=bl.shipId||shipData[0]?.id||'';setBL(c=>({...c,shipId:c.shipId||selectedShipId,productId:c.productId||productData[0]?.id||''}));await loadBLs(selectedShipId)}catch(e){setError(errorMessage(e))}}
  useEffect(()=>{void load()},[])
  async function submitShip(e:FormEvent){e.preventDefault();setError('');setMessage('');try{await createShip(shipName);setShipName('');setMessage('Nave creada correctamente.');await load()}catch(x){setError(errorMessage(x))}}
  async function submitProduct(e:FormEvent){e.preventDefault();setError('');setMessage('');try{await createProduct(productName);setProductName('');setMessage('Producto creado correctamente.');await load()}catch(x){setError(errorMessage(x))}}
  async function submitBL(e:FormEvent){e.preventDefault();setError('');setMessage('');const quantity=Number(bl.totalQuantity);if(!Number.isInteger(quantity)||quantity<=0){setError('La cantidad declarada debe ser un número entero mayor que cero.');return}try{await createBL(bl.code,quantity,bl.shipId,bl.productId);setBL(c=>({...c,code:'',totalQuantity:''}));setMessage('BL creado correctamente.');await loadBLs(bl.shipId)}catch(x){setError(errorMessage(x))}}
  async function submitUser(e:FormEvent){e.preventDefault();setError('');setMessage('');if(newUser.password.length<8){setError('La contraseña debe tener al menos 8 caracteres.');return}try{await createUser(newUser.uid,newUser.firstName,newUser.lastName,newUser.password,newUser.role);setNewUser({uid:'',firstName:'',lastName:'',password:'',role:3});setMessage('Usuario creado correctamente.');await load()}catch(x){setError(errorMessage(x))}}
  async function changeRole(item:UserSummary,role:number){setError('');setMessage('');if(item.uid===user?.uid&&role!==1){setError('No puedes quitarte tu propio rol de Administrador durante una sesión activa.');return}try{await updateUserRole(item.id,role);setMessage(`Rol de ${item.uid} actualizado.`);await load()}catch(x){setError(errorMessage(x))}}
  async function changeStatus(item:UserSummary){setError('');setMessage('');if(item.uid===user?.uid&&item.isActive){setError('No puedes desactivar tu propia cuenta durante una sesión activa.');return}const nextStatus=!item.isActive;try{await updateUserStatus(item.id,nextStatus);setMessage(`${item.uid} ${nextStatus?'activado':'desactivado'} correctamente.`);await load()}catch(x){setError(errorMessage(x))}}
  async function submitPasswordReset(e:FormEvent,item:UserSummary){e.preventDefault();setError('');setMessage('');if(resetPassword.length<8){setError('La contraseña debe tener al menos 8 caracteres.');return}try{await resetUserPassword(item.id,resetPassword);setResetPassword('');setResetUserId('');setMessage(`Contraseña de ${item.uid} restablecida correctamente.`)}catch(x){setError(errorMessage(x))}}
  function changeBLShip(shipId:string){setBL(c=>({...c,shipId}));setError('');void loadBLs(shipId)}
  if(user?.role!=='Administrator')return <main className="admin-shell"><p>Acceso exclusivo para Administradores.</p><button onClick={()=>navigate('/ships')}>Volver</button></main>
  return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">IQBF Control</span><h1>Administración</h1></div><button className="secondary-action" onClick={()=>navigate('/ships')}>Volver a operación</button></header>
    {error?<p className="operations-message operations-error">{error}</p>:null}{message?<p className="operations-message operations-success">{message}</p>:null}
    <div className="admin-grid">
      <section className="admin-card"><h2>Naves</h2><form onSubmit={submitShip}><label>Nombre<input value={shipName} onChange={e=>setShipName(e.target.value)} required/></label><button type="submit">Crear nave</button></form><p>{ships.length} nave(s) activa(s)</p></section>
      <section className="admin-card"><h2>Productos</h2><form onSubmit={submitProduct}><label>Nombre<input value={productName} onChange={e=>setProductName(e.target.value)} required/></label><button type="submit">Crear producto</button></form><ul>{products.map(p=><li key={p.id}>{p.name}</li>)}</ul></section>
      <section className="admin-card admin-bl"><h2>BL</h2><form onSubmit={submitBL}><label>Código<input value={bl.code} onChange={e=>setBL(c=>({...c,code:e.target.value}))} required/></label><label>Cantidad declarada (Big Bags)<input type="number" min="1" step="1" inputMode="numeric" value={bl.totalQuantity} onChange={e=>setBL(c=>({...c,totalQuantity:e.target.value}))} required/></label><label>Nave<select value={bl.shipId} onChange={e=>changeBLShip(e.target.value)} required>{ships.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Producto<select value={bl.productId} onChange={e=>setBL(c=>({...c,productId:e.target.value}))} required>{products.filter(p=>p.isActive).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button type="submit">Crear BL</button></form>
        <div className="admin-bl-list"><h3>BL registrados en la nave</h3>{bls.length===0?<p>No hay BL registrados para esta nave.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Código</th><th>Producto</th><th>Big Bags declarados</th><th>Estado</th></tr></thead><tbody>{bls.map(item=><tr key={item.id}><td><strong>{item.code}</strong></td><td>{item.productName}</td><td>{item.totalQuantity.toLocaleString('es-PE')}</td><td>{item.isActive?'Activo':'Inactivo'}</td></tr>)}</tbody></table></div>}</div>
      </section>
      <section className="admin-card admin-users"><h2>Usuarios</h2><form onSubmit={submitUser}><label>UID<input value={newUser.uid} onChange={e=>setNewUser(c=>({...c,uid:e.target.value}))} maxLength={50} autoComplete="off" required/></label><label>Nombre<input value={newUser.firstName} onChange={e=>setNewUser(c=>({...c,firstName:e.target.value}))} required/></label><label>Apellido<input value={newUser.lastName} onChange={e=>setNewUser(c=>({...c,lastName:e.target.value}))} required/></label><label>Contraseña temporal<input type="password" value={newUser.password} onChange={e=>setNewUser(c=>({...c,password:e.target.value}))} minLength={8} autoComplete="new-password" required/></label><label>Rol<select value={newUser.role} onChange={e=>setNewUser(c=>({...c,role:Number(e.target.value)}))}><option value={3}>User</option><option value={2}>Yard</option><option value={1}>Administrator</option></select></label><button type="submit">Crear usuario</button></form><hr/>
        {users.map(u=><div className="admin-user" key={u.id}><span><strong>{u.uid}</strong> · {u.fullName}</span><select aria-label={`Rol de ${u.uid}`} value={roleValue(u.role)} disabled={u.uid===user?.uid} onChange={e=>void changeRole(u,Number(e.target.value))}><option value={1}>Administrator</option><option value={2}>Yard</option><option value={3}>User</option></select><button type="button" className="secondary-action" disabled={u.uid===user?.uid} onClick={()=>void changeStatus(u)}>{u.isActive?'Desactivar':'Activar'}</button><button type="button" className="secondary-action" onClick={()=>{setResetUserId(resetUserId===u.id?'':u.id);setResetPassword('');setError('');setMessage('')}}>{resetUserId===u.id?'Cancelar':'Restablecer contraseña'}</button><small>{roleName(u.role)} · {u.isActive?'Activo':'Inactivo'}{u.uid===user?.uid?' · sesión actual':''}</small>{resetUserId===u.id?<form onSubmit={e=>void submitPasswordReset(e,u)}><label>Nueva contraseña temporal<input type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} minLength={8} autoComplete="new-password" required/></label><button type="submit">Guardar nueva contraseña</button></form>:null}</div>)}
      </section>
    </div></main>
}
